NUM_BPLEVELS = 50
NUM_XP_PER_LEVEL = 750

NUM_EPLOGUE_LEVELS = 5
NUM_EPLOGUE_XP_PER_LEVEL = 36500

LEVEL2_OFFSET = 500

DATA_PATH = "dat/data.json"
SETTINGS_PATH = "dat/settings.json"
OLD_DATA_PATH = "dat/config.json"

UPDATER_PATH = "Updater.exe"
VERSION_PATH = "version.json"
OLD_VERSION_PATH = "version"

APP_NAME = "VexTrack"
WINDOW_GEOMETRY = "700x640"

GITHUB_USER = "BitTim"
GITHUB_REPO = APP_NAME
EXE_FILENAME = APP_NAME + ".exe"

LEGACY_VERSIONS = [APP_NAME, "Updater"]
LEGACY_LAST_APP = 1.4
LEGACY_LAST_UPDATER = 1.15

# ================================
#  Default Settings
# ================================

DEFAULT_BUFFER_DAYS = 8
DEFAULT_USE_HISTORY_COLORS = 1
DEFAULT_IGNORE_INACTIVE_DAYS = 0
DEFAULT_IGNORE_PRERELEASES = 1

DEFAULT_NONE_BG_COLOR = "#939393"
DEFAULT_WIN_BG_COLOR = "#AFE0D2"
DEFAULT_LOSS_BG_COLOR = "#F7AAA8"
DEFAULT_DRAW_BG_COLOR = "#C3C3C3"
DEFAULT_SELECTED_BG_COLOR = "#0078D7"

DEFAULT_NONE_FG_COLOR = "#000000"
DEFAULT_WIN_FG_COLOR = "#000000"
DEFAULT_LOSS_FG_COLOR = "#000000"
DEFAULT_DRAW_FG_COLOR = "#000000"
DEFAULT_SELECTED_FG_COLOR = "#FFFFFF"