const coreError = (errorCode: string) => {
	switch (errorCode)
	{
		case "FILE_NULL":
			alert("File cannot be empty");
			break;
		case "GOALS_NULL":
			alert("Invalid file: File does not include goals. Please make sure to use a data.json generated by version v1.86 or v1.87");
			break;
		case "STREAK_NULL":
			alert("Invalid file: File does not include streak. Please make sure to use a data.json generated by version v1.86 or v1.87");
			break;
		case "SEASONS_NULL":
			alert("Invalid file: File does not include seasons. Please make sure to use a data.json generated by version v1.86 or v1.87");
			break;
		case "SEASONS_EMPTY":
			alert("Invalid file: File includes empty field for seasons. Please make sure, that the file includes at least 1 season");
			break;
		case "LEGACY_SEASONS":
			alert("Invalid file: File includes old season format. Please make sure to use a data.json generated by version v1.86 or v1.87");
			break;
		default:
			alert("Something went wrong: " + errorCode);
			break;
	}
}

export { coreError };