// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS7RFzIh5NBqC8dAZaDNtEVSWeeoutvVI',
    appId: '1:280952778332:web:fd54b720bbc8d1f8634099',
    messagingSenderId: '280952778332',
    projectId: 'vextrack-bt',
    authDomain: 'vextrack-bt.firebaseapp.com',
    storageBucket: 'vextrack-bt.appspot.com',
    measurementId: 'G-GHJCP82QZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGuBf1HbqZOpgWTPBcWaCd5zP4zAz-_Cc',
    appId: '1:280952778332:android:61b6e18425387f2c634099',
    messagingSenderId: '280952778332',
    projectId: 'vextrack-bt',
    storageBucket: 'vextrack-bt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy47WUhUu25tHx-V7XQblS_nWuP2pOmbA',
    appId: '1:280952778332:ios:810a275d99a9a1b9634099',
    messagingSenderId: '280952778332',
    projectId: 'vextrack-bt',
    storageBucket: 'vextrack-bt.appspot.com',
    iosClientId: '280952778332-vegvfvtd2nst7mhq51oeuj4d41bedh7s.apps.googleusercontent.com',
    iosBundleId: 'tech.bittim.vextrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy47WUhUu25tHx-V7XQblS_nWuP2pOmbA',
    appId: '1:280952778332:ios:810a275d99a9a1b9634099',
    messagingSenderId: '280952778332',
    projectId: 'vextrack-bt',
    storageBucket: 'vextrack-bt.appspot.com',
    iosClientId: '280952778332-vegvfvtd2nst7mhq51oeuj4d41bedh7s.apps.googleusercontent.com',
    iosBundleId: 'tech.bittim.vextrack',
  );
}
