NUM_BPLEVELS = 50
NUM_XP_PER_LEVEL = 750

NUM_EPLOGUE_LEVELS = 5
NUM_EPLOGUE_XP_PER_LEVEL = 36500

LEVEL2_OFFSET = 500
BUFFER_DAYS = 8

CONFIG_PATH = "dat/config.json"
UPDATER_PATH = "Updater.exe"
VERSION_PATH = "version.json"
OLD_VERSION_PATH = "version"

APP_NAME = "VexTrack"
WINDOW_GEOMETRY = "700x640"

GITHUB_USER = "BitTim"
GITHUB_REPO = APP_NAME
EXE_FILENAME = APP_NAME + ".exe"

LEGACY_VERSIONS = [APP_NAME, "Updater"]
LEGACY_LAST_APP = 1.4
LEGACY_LAST_UPDATER = 1.15

WIN_BG_COLOR = "#AFE0D2"
WIN_FG_COLOR = "#000000"
LOSS_BG_COLOR = "#F7AAA8"
LOSS_FG_COLOR = "#000000"
SELECTED_BG_COLOR = "#0078D7"
SELECTED_FG_COLOR = "#FFFFFF"