NUM_BPLEVELS = 50
NUM_XP_PER_LEVEL = 750

NUM_EPLOGUE_LEVELS = 5
NUM_EPLOGUE_XP_PER_LEVEL = 36500

LEVEL2_OFFSET = 500
BUFFER_DAYS = 8

CONFIG_PATH = "dat/config.json"
UPDATER_PATH = "Updater.exe"
VERSION_PATH = "version.json"
OLD_VERSION_PATH = "version"

WINDOW_TITLE = "Vex Track"
WINDOW_GEOMETRY = "700x640"

GITHUB_USER = "BitTim"
GITHUB_REPO = "VexTrack"
EXE_FILENAME = "VexTrack.exe"