NUM_BPLEVELS = 50
NUM_XP_PER_LEVEL = 750

NUM_EPLOGUE_LEVELS = 5
NUM_EPLOGUE_XP_PER_LEVEL = 36500

LEVEL2_OFFSET = 500
BUFFER_DAYS = 8

CONFIG_PATH = "dat/config.json"

WINDOW_TITLE = "Valorant XP Calculator"
WINDOW_GEOMETRY = "700x640"